# file to store some often use functions

import os, sys, shutil
import os.path as osp


def renew_dir(target_dir):
    if osp.exists(target_dir):
        shutil.rmtree(target_dir)
    os.makedirs(target_dir)


def remove_swp(in_dir):
    ''' This function is used to remove all the swp files 
        generated by vim in a directory '''
    remove_files = list()
    for subdir, dirs, files in os.walk(in_dir):
        for file in files:
            if file.endswith('.swp'):
                full_path = osp.join(subdir,file)
                os.remove(full_path)


def generate_print_code(code_line):
    assert( type(code_line) == str )
    record = code_line.strip().split(',')
    for variable_name in record:
        print(" print('{0}', {0}) ".format(variable_name))


def easy_parallel(target_func, all_args):
    ''' Avoid to write this code each time '''
    process_list = list()
    for args in all_args:
        p = mp.Process(target=target_func, args=args)
        p.start()
        process_list.append(p)
    for p in process_list:
        p.join()
