# file to store some often use functions

import os, sys, shutil
import os.path as osp


def print_vars(_locals, variables, func):
    '''
    print variable in the variables,
    the format is [name_of_variable, value_of_variable]
    useage:
    print_vars(locals(), variables)
    '''
    print('------------------------------------')
    var_list = list()
    for name, variable in list(_locals.items()):
        if variable in variables:
            idx = variables.index(variable)
            var_list.append( (name, variable, idx) )

    sorted_var_list = sorted(var_list, key=lambda a:a[2])
    for name, variable, _ in sorted_var_list:
        print("{}\t{}".format(name, func(variable)))
    print('------------------------------------')


def renew_dir(target_dir):
    if osp.exists(target_dir):
        shutil.rmtree(target_dir)
    os.makedirs(target_dir)


def remove_swp(in_dir):
    ''' This function is used to remove all the swp files 
        generated by vim in a directory '''
    remove_files = list()
    for subdir, dirs, files in os.walk(in_dir):
        for file in files:
            if file.endswith('.swp'):
                full_path = osp.join(subdir,file)
                os.remove(full_path)


def generate_print_code(code_line):
    assert( type(code_line) == str )
    record = code_line.strip().split(',')
    for variable_name in record:
        print(" print('{0}', {0}) ".format(variable_name))
